#' Generates a Resolvable Row-Column Design (RowColD)
#'
#'
#' @description It randomly generates a resolvable row-column design (RowColD).
#'  The design is optimized in both rows and columns blocking factors. The 
#'  randomization can be done across multiple locations.
#' 
#' @details
#' With \code{method = "twostage"}, the Row-Column design is built in two
#' stages. The first step 
#' constructs the blocking factor \code{Columns} using Incomplete Block Units 
#' from an incomplete block design that sets the number of incomplete blocks as 
#' the number of \code{Columns} in the design, each of which has a dimension 
#' equal to the number of \code{Rows}. Once this design is generated, the 
#' \code{Rows} are used as the \code{Row} blocking factor that is optimized for 
#' A-Efficiency, but levels within the original \code{Columns} are fixed.
#' To optimize the \code{Rows} while maintaining the current optimized \code{Columns}, 
#' we use a heuristic algorithm that swaps at random treatment positions within 
#' a given \code{Column (Block)} also selected at random. The algorithm begins 
#' by calculating the A-Efficiency on the initial design, performs a swap iteration, 
#' recalculates the A-Efficiency on the resulting design, and compares it with 
#' the previous one to decide whether to keep or discard the new design. This
#' iterative process is repeated, by default, 1,000 times. This two-stage
#' greedy search reproduces the designs generated by previous versions of
#' FielDHub and is available via \code{method = "twostage"}.
#'
#' When \code{method = "onestage"} (the default, also called simultaneous),
#' the rows and columns are optimized jointly in a single stage with
#' \code{blocksdesign::design()} instead of optimizing the columns first and the
#' rows afterwards. The joint row-by-column A-Efficiency of the standard analysis
#' model (rows and columns adjusted together) is reported as the
#' \code{Row-by-Column} row of \code{blocksModel}. With the default
#' \code{latinize = FALSE} the joint optimization targets this within-replicate
#' criterion and typically increases it relative to \code{"twostage"}; with
#' \code{latinize = TRUE} it instead targets the across-replicate latinization
#' described below. The per-factor (marginal) \code{Row} and \code{Column}
#' A-Efficiencies are already close to optimal under both methods and differ only
#' slightly between them (and not systematically in one direction). The size of
#' the joint gain is layout-dependent and tends to be largest for small designs
#' with few replicates. For \code{method = "onestage"}, the \code{iterations}
#' argument is passed to \code{blocksdesign::design()} as its number of
#' \code{searches}. For a very small design, the joint one-stage model can be
#' over-parameterized (no residual degrees of freedom); in that case
#' \code{row_column()} issues a warning and automatically falls back to
#' \code{method = "twostage"} rather than failing, so a design is still
#' produced.
#'
#' Setting \code{latinize = TRUE} (only available with \code{method =
#' "onestage"}) codes the rows and columns as crossed blocking factors shared
#' across the replicates, so that a treatment tends to occupy different rows and
#' different columns in the different replicates (a latinized resolvable
#' row-column design in the sense of John and Williams). This guards against the
#' same treatment recurring in the same field row or column over the whole trial,
#' not just within a replicate, and is useful when a field trend runs along the
#' whole-field rows or columns. It optimizes a different (crossed) model than the
#' default nested one, so the two are not directly comparable, and full
#' latinization is only possible when there are at least as many rows and columns
#' as replicates. By default (\code{latinize = FALSE}) the rows and columns stay
#' nested within each replicate. \code{latinize} has no effect for
#' \code{method = "twostage"}, which cannot latinize across replicates.
#'
#' @param t Number of  treatments.
#' @param nrows Number of rows of a full resolvable replicate. 
#' @param r Number of blocks (full resolvable replicates).
#' @param l Number of locations. By default \code{l = 1}.
#' @param plotNumber Numeric vector with the starting plot number for each 
#' location. By default \code{plotNumber = 101}.
#' @param seed (optional) Real number that specifies the starting seed to obtain 
#' reproducible designs.
#' @param locationNames (optional) Names for each location.
#' @param iterations Number of optimization iterations. Its meaning and default
#' depend on \code{method}. For \code{method = "onestage"} it is passed to
#' \code{blocksdesign::design()} as its number of \code{searches} (default 200;
#' values beyond a few hundred rarely improve the design). For
#' \code{method = "twostage"} it is the number of greedy row-swap iterations
#' (default 1000). If \code{NULL} (the default), a value appropriate to the
#' chosen \code{method} is used.
#' @param data (optional) Data frame with label list of treatments
#' @param method Optimization strategy for the row and column blocking factors.
#' Either \code{"onestage"} (default) or \code{"twostage"}. With
#' \code{"onestage"} (also known as simultaneous) the rows and columns are
#' optimized jointly with \code{blocksdesign::design()}, which usually yields a
#' higher joint row-by-column A-Efficiency while leaving the per-factor row and
#' column efficiencies almost unchanged (see Details and the
#' \code{Row-by-Column} row of \code{blocksModel}); for \code{"onestage"} the
#' \code{iterations} argument is passed as the number of \code{searches} to
#' \code{blocksdesign::design()}. With \code{"twostage"} the columns are
#' optimized first and the rows are then improved by a greedy search, keeping
#' the columns fixed; this reproduces the designs generated by previous versions
#' of FielDHub. \code{"onestage"} automatically falls back to \code{"twostage"}
#' (with a warning) for very small designs whose joint one-stage model is
#' over-parameterized, so \code{"twostage"} rarely has to be requested
#' explicitly.
#' @param latinize If \code{TRUE}, optimize the row and column blocking factors
#' as crossed (latinized) effects shared across the replicates, so that each
#' treatment tends to appear in different rows and columns across the replicates.
#' By default \code{FALSE}. Only meaningful with \code{method = "onestage"}; it
#' is ignored for \code{method = "twostage"} (which cannot latinize across
#' replicates), where passing \code{latinize = TRUE} is ignored with a warning.
#'
#' @author Didier Murillo [aut],
#'         Salvador Gezan [aut],
#'         Ana Heilman [ctb],
#'         Thomas Walk [ctb], 
#'         Johan Aparicio [ctb], 
#'         Richard Horsley [ctb]
#' 
#' 
#' @importFrom stats runif na.omit
#' 
#' @return A list with five elements.
#' \itemize{
#'   \item \code{infoDesign} is a list with information on the design parameters.
#'   \item \code{blocksModel} is a list (one element per location) with the
#'   efficiency of the design. In addition to the per-factor \code{Rep},
#'   \code{Row} and \code{Column} A- and D-Efficiencies, it reports a
#'   \code{Row-by-Column} row with the joint A- and D-Efficiency of the standard
#'   resolvable row-column analysis model (rows and columns adjusted together).
#'   \item \code{resolvableBlocks} a list with the resolvable row columns blocks.
#'   \item \code{concurrence} is the concurrence matrix.
#'   \item \code{fieldBook} is a data frame with the row-column field book.
#' }
#'
#'
#' @references
#' Edmondson., R. N. (2021). blocksdesign: Nested and crossed block designs for 
#' factorial and unstructured treatment sets. https://CRAN.R-project.org/package=blocksdesign
#'
#' @examples
#' 
#' # Example 1: Generates a row-column design with 2 full blocks and 24 treatments
#' # and 6 rows, for one location. This uses the default method = "onestage", for
#' # which a small number of iterations (passed as searches) already captures most
#' # of the joint-efficiency gain.
#' rowcold1 <- row_column(
#'   t = 24, 
#'   nrows = 6, 
#'   r = 2, 
#'   l = 1, 
#'   plotNumber= 101, 
#'   locationNames = "Loc1",
#'   iterations = 20,
#'   seed = 21
#' )
#' rowcold1$infoDesign
#' rowcold1$resolvableBlocks
#' head(rowcold1$fieldBook,12)
#' 
#' # Example 2: Generates a row-column design with 2 full blocks and 30 treatments
#' # and 5 rows, for one location, using the default method = "onestage".
#' # In this case, we show how to use the option data.
#' treatments <- paste("ND-", 1:30, sep = "")
#' ENTRY <- 1:30
#' treatment_list <- data.frame(list(ENTRY = ENTRY, TREATMENT = treatments))
#' head(treatment_list)
#' rowcold2 <- row_column(
#'   t = 30, 
#'   nrows = 5, 
#'   r = 2, 
#'   l = 1, 
#'   plotNumber= 1001, 
#'   locationNames = "A",
#'   seed = 15,
#'   iterations = 20,
#'   data = treatment_list
#' )
#' rowcold2$infoDesign
#' rowcold2$resolvableBlocks
#' head(rowcold2$fieldBook,12)
#'
#' # Example 3: Same design as Example 1 but using the historical two-stage
#' # optimization (method = "twostage"), which reproduces the designs generated
#' # by previous versions of FielDHub. For twostage, iterations is the number of
#' # greedy row-swap iterations; its default is 1000, but a smaller value is
#' # used here to keep the example quick.
#' rowcold3 <- row_column(
#'   t = 24,
#'   nrows = 6,
#'   r = 2,
#'   l = 1,
#'   plotNumber = 101,
#'   locationNames = "Loc1",
#'   iterations = 100,
#'   method = "twostage",
#'   seed = 21
#' )
#' rowcold3$infoDesign
#' # The Row-by-Column row reports the joint row-by-column A-Efficiency.
#' rowcold3$blocksModel
#' head(rowcold3$fieldBook, 12)
#'
#'
#' @export
row_column <- function(t = NULL, nrows = NULL, r = NULL, l = 1, plotNumber= 101,
                       locationNames = NULL, seed = NULL, iterations = NULL,
                       data = NULL, method = c("onestage", "twostage"),
                       latinize = FALSE) {

  method <- match.arg(method)
  # iterations has a method-specific meaning and default: for "onestage" it is
  # the number of blocksdesign::design() searches (a few hundred already
  # captures the gain), for "twostage" the number of greedy row-swap iterations.
  # When left NULL, pick a value appropriate to the method.
  if (is.null(iterations)) {
    searches_onestage <- 200L
    iterations_twostage <- 1000L
  } else {
    if (!is.numeric(iterations) || length(iterations) != 1 || is.na(iterations) ||
        iterations < 1) {
      shiny::validate('row_column() requires iterations to be a single positive integer.')
    }
    searches_onestage <- iterations
    iterations_twostage <- iterations
  }
  # latinize is only meaningful for method = "onestage" (the two-stage greedy
  # search cannot latinize across replicates); for method = "twostage" it is
  # ignored, with a warning if it was explicitly set to TRUE.
  if (!is.logical(latinize) || length(latinize) != 1 || is.na(latinize)) {
    shiny::validate('row_column() requires latinize to be TRUE or FALSE.')
  }
  if (latinize && method == "twostage") {
    warning('latinize is only available with method = "onestage"; ',
            'it is ignored for method = "twostage".', call. = FALSE)
    latinize <- FALSE
  }
  if (is.null(seed) || !is.numeric(seed)) seed <- runif(1, min = -50000, max = 50000)
  # set.seed(seed)
  k <- nrows
  lookup <- FALSE
  if (is.null(data)) {
    if (is.null(t) || is.null(k) || is.null(r) || is.null(l)) {
      shiny::validate('Some of the basic design parameters are missing (t, k, r or l).')
    }
    arg1 <- list(k, r, l);arg2 <- c(k, r, l)
    if (base::any(lengths(arg1) != 1) || base::any(arg2 %% 1 != 0) || base::any(arg2 < 1)) {
      shiny::validate('row_column() requires k, r and l to be possitive integers.')
    }
    if (is.numeric(t)) {
      if (length(t) == 1) {
        if (t == 1 || t < 1) {
          shiny::validate('row_column() requires more than one treatment.')
        } 
        nt <- t
      }else if ((length(t) > 1)) {
        nt <- length(t)
        TRT <- t
      }
    } else if (is.character(t) || is.factor(t)) {
      if (length(t) == 1) {
        shiny::validate('incomplete_blocks() requires more than one treatment.')
      } 
      nt <- length(t)
    } else if ((length(t) > 1)) {
      nt <- length(t)
    }
    data_up <- data.frame(list(ENTRY = 1:nt, TREATMENT = paste0("G-", 1:nt)))
    colnames(data_up) <- c("ENTRY", "TREATMENT")
    lookup <- TRUE
    df <- data.frame(list(ENTRY = 1:nt, LABEL_TREATMENT = paste0("G-", 1:nt)))
    dataLookUp <- df
  } else if (!is.null(data)) {
    if (is.null(t) || is.null(r) || is.null(k) || is.null(l)) {
      shiny::validate('Some of the basic design parameters are missing (t, r, k or l).')
    }
    if(!is.data.frame(data)) shiny::validate("Data must be a data frame.")
    data_up <- as.data.frame(data[,c(1,2)])
    data_up <- na.omit(data_up)
    colnames(data_up) <- c("ENTRY", "TREATMENT")
    data_up$TREATMENT <- as.character(data_up$TREATMENT)
    new_t <- length(data_up$TREATMENT)
    if (t != new_t) base::stop("Number of treatments do not match with data input.")
    TRT <- data_up$TREATMENT
    nt <- length(TRT)
    lookup <- TRUE
    dataLookUp <- data.frame(list(ENTRY = 1:nt, LABEL_TREATMENT = TRT))
  }
  if (k >= nt) shiny::validate('incomplete_blocks() requires k < t.')
  if (nt %% k != 0) {
    shiny::validate('Number of treatments can not be fully distributed over the specified incomplete block specification.')
  }
  if(is.null(locationNames) || length(locationNames) != l) locationNames <- 1:l
  nunits <- k
  # For method = "onestage" with latinize = TRUE, full latinization (no treatment
  # repeating a row or a column across the replicates) is only possible when
  # there are at least as many rows and columns as replicates; otherwise the
  # optimizer still runs but cannot avoid every clash.
  if (latinize) {
    ncols_full <- nt / nunits
    if (r > nrows || r > ncols_full) {
      warning('With latinize = TRUE, full latinization requires r <= nrows and ',
              'r <= ncols (here r = ', r, ', nrows = ', nrows, ', ncols = ',
              ncols_full, '), so some treatments will still repeat a row or a ',
              'column across replicates.', call. = FALSE)
    }
  }


  ## New code
  N <- nt * r
  out_row_col_loc <- vector(mode = "list", length = l)
  blocks_model <- list()
  for (i in 1:l) {
    reps <- r
    ncols <- nt / nunits
    if (method == "onestage") {
      # One-stage: optimize rows and columns jointly with design(). If the joint
      # model is over-parameterized for a design this small, design() errors;
      # rather than failing, fall back to the two-stage method with a warning so
      # small designs (and the Shiny app, which does not expose method) still
      # produce a design. The dimensions are identical across locations, so the
      # fallback, once triggered, applies to the remaining locations too.
      onestage_fit <- tryCatch(
        build_row_column_onestage(
          nt = nt, nrows = nrows, ncols = ncols, reps = reps,
          latinize = latinize, searches = searches_onestage, seed = seed + i
        ),
        onestage_infeasible = function(cnd) cnd
      )
      if (inherits(onestage_fit, "onestage_infeasible")) {
        warning('method = "onestage" is not feasible for these dimensions ',
                '(t = ', nt, ', nrows = ', nrows, ', r = ', r, '): the joint ',
                'one-stage row-and-column model is over-parameterized, so ',
                'row_column() falls back to method = "twostage". ',
                'blocksdesign::design() reported: ',
                conditionMessage(onestage_fit), call. = FALSE)
        method <- "twostage"
      } else {
        field_book_best_design <- onestage_fit
      }
    }
    if (method == "twostage") {
      # Two-stage: build columns with blocks(), then greedily optimize rows.
      mydes <- blocksdesign::blocks(
        treatments = nt,
        replicates = reps,
        blocks = list(reps, ncols),
        seed = seed + i
      )
      mydes <- rerandomize_ibd(ibd_design = mydes)
      # Create row and column design
      row_col_design <- mydes$Design_new |>
        dplyr::mutate(Level_3 = rep(rep(paste0("B", 1:nrows), times = ncols), times = reps)) |>
        dplyr::mutate(Level_3 = paste(Level_1, Level_3, sep = ".")) |>
        dplyr::mutate(Level_3 = factor(Level_3, levels = unique(Level_3))) |>
        dplyr::select(Level_1, Level_2, Level_3, plots, treatments)

      improved_design <- improve_efficiency(row_col_design, iterations_twostage, seed = seed + i)
      field_book_best_design <- improved_design$best_design
    }
    row_column_efficiency <- report_efficiency(field_book_best_design)
    blocks_model[[i]] <- row_column_efficiency
    row_col_fieldbook <- field_book_best_design |>
      dplyr::rename(
        REP = Level_1, 
        COLUMN = Level_2, 
        ROW = Level_3, 
        PLOT = plots, 
        ENTRY = treatments) |>
      dplyr::mutate(
        REP = as.numeric(factor(REP, levels = unique(REP)))
      ) |> 
      dplyr::group_by(REP) |>
      dplyr::mutate(
        COLUMN = as.numeric(factor(COLUMN, levels = unique(COLUMN))),
        ROW = as.numeric(factor(ROW, levels = unique(ROW)))
      ) |>
      dplyr::select(PLOT, REP, COLUMN, ROW, ENTRY)
    
    locations_df <- data.frame(list(LOCATION = rep(locationNames[i], each = N)))
    row_col_fieldbook <- dplyr::bind_cols(locations_df, row_col_fieldbook)
    out_row_col_loc[[i]] <- row_col_fieldbook
  
  }
  
  out_row_col <- dplyr::bind_rows(out_row_col_loc)
  out_row_col$ENTRY <- as.numeric(out_row_col$ENTRY)
  
  if (lookup) {
    out_row_col <- dplyr::inner_join(out_row_col, dataLookUp, by = "ENTRY")
    out_row_col <- out_row_col |> 
      dplyr::rename(TREATMENT = LABEL_TREATMENT) |> 
      dplyr::select(-ENTRY)
    out_row_col <- dplyr::inner_join(out_row_col, data_up, by = "TREATMENT") |> 
      dplyr::select(LOCATION, PLOT, REP, ROW, COLUMN, ENTRY, TREATMENT)
  }
  
  out_row_col_id <- out_row_col
  
  out_row_col_id <- out_row_col_id[order(out_row_col_id$LOCATION, out_row_col_id$REP, out_row_col_id$ROW),]
  row_col_plots <- ibd_plot_numbers(nt = nt, plot.number = plotNumber, r = r, l = l)
  out_row_col_id$PLOT <- as.vector(unlist(row_col_plots))
  
  ID <- 1:nrow(out_row_col_id)
  out_row_col_fieldbook <- cbind(ID, out_row_col_id)
  
  loc <- levels(out_row_col_fieldbook$LOCATION)
  ib <- nt/k
  Resolvable_rc_reps <- vector(mode = "list", length = r*l)
  w <- 1
  for (sites in 1:l) {
    for (j in 1:r) {
      z <- out_row_col_fieldbook
      z <- subset(z, z$LOCATION == loc[sites] & z$REP == j)
      if (is.null(data)){
        Resolvable_rc_reps[[w]] <- matrix(data = as.vector(z$ENTRY), nrow = nunits,
                                          ncol = ib, byrow = TRUE)
      }else {
        Resolvable_rc_reps[[w]] <- matrix(data = as.vector(z$TREATMENT), nrow = nunits,
                                          ncol = ib, byrow = TRUE)
      }
      w <- w + 1
    }
  }
  NEW_Resolvable <- setNames(vector(mode = "list", length = l),
                             paste0("Loc_", locationNames))
  x <- seq(1, r * l, r)
  y <- seq(r, r * l, r)
  z <- 1
  for (loc in 1:l) {
    NEW_Resolvable[[loc]] <- setNames(Resolvable_rc_reps[x[z]:y[z]],
                                 paste0(rep("rep", r), 1:r))
    z <- z + 1
  }

  df <- out_row_col_fieldbook
  trt <- "ENTRY"
  c1 <- concurrence_matrix(df=df, trt=trt, target='REP')
  c2 <- concurrence_matrix (df=df, trt=trt, target='ROW')
  c3 <- concurrence_matrix (df=df, trt=trt, target='COLUMN')
  summ <- merge(c1, c2, by="Concurrence", all=TRUE)
  new_summ <- merge(summ, c3, by='Concurrence', all=TRUE)
  infoDesign <- list(
    rows = nrows,
    columns = ib,
    reps = r,
    treatments = nt,
    locations = l,
    location_names = locationNames,
    seed = seed,
    optimization = method,
    id_design = 9
  )
  output <- list(
    infoDesign = infoDesign,
    blocksModel = blocks_model,
    resolvableBlocks = NEW_Resolvable,
    concurrence = new_summ,
    fieldBook = out_row_col_fieldbook
  )
  class(output) <- "FielDHub"
  return(invisible(output))
}