#' @title Optimized multi-location partially replicated design
#' @param lines Number of genotypes, experimental lines or treatments.
#' @param copies_per_entry Number of total copies per treatment.
#' @param desired_avg (optional) Desired average of treatments across locations.
#' @param checks Number of checks.
#' @param rep_checks Number of replications per check.
#' @param planter Option for \code{serpentine} or \code{cartesian} movement. By default  \code{planter = 'serpentine'}.
#' @param l Number of locations. By default \code{l = 1}.
#' @param plotNumber Numeric vector with the starting plot number for each location. By default \code{plotNumber = 101}.
#' @param exptName (optional) Name of the experiment.
#' @param locationNames (optional) Name for each location.
#' @param nrows Numeric vector with the number of rows field at each location.
#' @param ncols Numeric vector with the number of columns field at each location.
#' @param seed (optional) Real number that specifies the starting seed to obtain reproducible designs.
#' @param spread_reps A logical value indicating whether to maximize the spatial
#'   distance between replicated treatments in the field. Default is \code{TRUE}.
#' @param optim_list (optional) A list object of class "MultiPrep"generated by \code{do_optim()} function.
#' @param data (optional) Data frame with 2 columns: \code{ENTRY | NAME }. ENTRY must be numeric.
#' @param allow_fillers A logical value indicating whether field dimensions may
#'   exceed the number of experimental plots. Fillers occupy the terminal cells
#'   of the selected planter path. Default is \code{FALSE}.
#' @param max_fillers Maximum number of filler plots considered when dimensions
#'   are selected automatically. When \code{NULL}, up to 10 filler plots are
#'   considered.
#'
#'
#' @author Didier Murillo [aut],
#'         Salvador Gezan [aut],
#'         Jean-Marc Montpetit [ctb],
#'         Ana Heilman [ctb]
#'
#' @param year (optional) Year recorded in the \code{YEAR} column of the field book.
#' By default the current year.
#' @return A list of class \code{FielDHub} with several elements.
#' \itemize{
#'   \item \code{infoDesign} is a list with information on the design parameters.
#'   \item \code{layoutRandom} is a matrix with the randomization layout.
#'   \item \code{plotNumber} is a matrix with the layout plot number.
#'   \item \code{binaryField} is a matrix with the binary field.
#'   \item \code{fillerField} is a logical matrix identifying filler plots.
#'   \item \code{dataEntry} is a data frame with the data input.
#'   \item \code{genEntries} is a list with the entries for replicated and non-replicated parts.
#'   \item \code{fieldBook} is a data frame with field book design. This includes the index (Row, Column).
#'   \item \code{min_pairwise_distance} is a data frame with the minimum pairwise distance between
#'              each pair of locations.
#'   \item \code{reps_info} is a data frame with information on the number of replicated and
#'              non-replicated treatments at each location.
#'   \item \code{pairsDistance} is a data frame with the pairwise distances between each pair of
#'              treatments.
#'   \item \code{treatments_with_reps} is a list with the entries for the replicated part of the design.
#'   \item \code{treatments_with_no_reps} is a list with the entries for the non-replicated part of the design.
#'   \item \code{list_locs} is a list with each location list of entries.
#'   \item \code{multi_location_data} is a data frame with the entries of every
#'              location: \code{LOCATION | ENTRY | NAME | REPS}.
#'   \item \code{allocation} is a matrix with the allocation of treatments.
#'   \item \code{size_locations} is a named vector with the size of each location.
#' }
#'
#' @references
#' Edmondson, R.N. Multi-level Block Designs for Comparative Experiments. JABES 25,
#' 500–522 (2020). https://doi.org/10.1007/s13253-020-00416-0
#'
#'
#' @examples
#' # Example 1: Generates a spatially optimized multi-location p-rep design with 142
#' # genotypes. The number of copies per plant available for this experiment is 9.
#' # This experiment is carried out in 5 locations, and there are seven seeds available
#' # for each plant to make replications.
#' # In this case, we add three controls (checks) with six reps each.
#' # With this setup, the experiment will have 142 treatments + 3 checks = 145
#' # entries and the number of plots per location after the allocation process
#' # will be 196.
#' # The average genotype allocation will be 1.5 copies per location.
#'\dontrun{
#' optim_multi_prep <- multi_location_prep(
#'   lines = 150,
#'   l = 5,
#'   copies_per_entry = 7,
#'   checks = 3,
#'   rep_checks = c(6,6,6),
#'   locationNames = c("LOC1", "LOC2", "LOC3", "LOC4", "LOC5"),
#'   seed = 1234
#' )
#' field_book <- optim_multi_prep$fieldBook
#' head(subset(field_book, LOCATION == "LOC1"), 10)
#' }
#' @section Reproducibility:
#' The result records effective inputs and the resolved seed in
#' \code{metadata$parameters}. Under the same package versions and RNG
#' settings, rebuild a result \code{x} with
#' \code{do.call(multi_location_prep, x$metadata$parameters)}.
#'
#' @export
multi_location_prep <- function(
    lines,
    nrows,
    ncols,
    l,
    planter = "serpentine",
    plotNumber,
    desired_avg,
    copies_per_entry,
    checks = NULL,
    rep_checks = NULL,
    exptName,
    locationNames,
    optim_list,
    seed,
    spread_reps = TRUE,
    data = NULL,
    allow_fillers = FALSE,
    max_fillers = NULL,
    year = NULL) {
    validate_locations(l)
    validate_flag(spread_reps, "spread_reps")
    validate_flag(allow_fillers, "allow_fillers")
    year <- resolve_year(year)
    # set a random seed if it is missing
    if (missing(seed)) seed <- NULL
    seed <- resolve_seed(seed, default = function() sample.int(10000, size = 1))
    local_design_seed(seed)
    if (missing(l)) fieldhub_abort("Please, define the number of locations for this design.")
    if (missing(locationNames) || length(locationNames) != l) {
        default_names <- paste0("LOC", 1:l)
        if (!missing(locationNames)) {
            warn_default_location_names(locationNames, l, default_names)
        }
        locationNames <- default_names
    }
    validate_location_labels(locationNames, l)
    if (missing(plotNumber) || length(plotNumber) != l) {
        default_plots <- default_plot_starts(l, 1)
        if (!missing(plotNumber)) {
            warn_default_plot_numbers(plotNumber, l, default_plots)
        }
        plotNumber <- default_plots
    }
    if (missing(exptName)) exptName <- "PrepExpt"
    if (missing(planter) || is.null(planter)) planter <- "serpentine"
    validate_planter(planter)
    if (missing(copies_per_entry) && missing(desired_avg)) {
        fieldhub_abort("multi_location_prep() requires either the argument copies_per_entry or desired_avg.")
    }
    if (missing(copies_per_entry)) {
        if (!is.numeric(desired_avg) || !is.null(dim(desired_avg)) ||
            length(desired_avg) != 1L || !is.finite(desired_avg) || desired_avg <= 0) {
            fieldhub_abort("`desired_avg` must be one finite positive number.",
                           data = list(argument = "desired_avg"))
        }
        copies_per_entry <- ceiling(l * desired_avg)
    }
    add_checks <- FALSE
    if (!is.null(checks) && !is.null(rep_checks)) add_checks <- TRUE
    if (!missing(optim_list)) {
        if (!inherits(optim_list, "MultiPrep")) {
            fieldhub_abort("sparse_list must be an object of class 'MultiPrep'")
        }
        preps <- optim_list
    } else {
        preps <- do_optim(
            design = "prep",
            lines = lines,
            l = l,
            copies_per_entry = copies_per_entry,
            add_checks = add_checks,
            checks = checks,
            rep_checks = rep_checks,
            seed = seed,
            data = data
        )
    }
    # Merge user input data
    if (!is.null(data)) {
        preps <- merge_user_data(
            optim_out = preps,
            data = data,
            lines = lines,
            add_checks = add_checks,
            checks = checks,
            rep_checks = rep_checks
        )
    }
    # Set the number of rows and columns
    if (missing(nrows) || missing(ncols)) {
        experimental_plots <- vapply(
            preps$list_locs,
            function(site_data) sum(as.numeric(site_data$REPS)),
            numeric(1)
        )
        nrows <- numeric(l)
        ncols <- numeric(l)
        for (site in seq_len(l)) {
            options <- prep_dimension_options(
                total_plots = experimental_plots[site],
                allow_fillers = allow_fillers,
                max_fillers = max_fillers
            )
            if (is.null(options)) {
                fieldhub_abort(
                    "There are no field dimension options available. ",
                    "Please specify nrows and ncols or allow filler plots."
                )
            }
            nrows[site] <- options$rows[1]
            ncols[site] <- options$columns[1]
        }
    }
    # Generate the p-rep randomization
    design_randomization <- partially_replicated(
        nrows = nrows,
        ncols = ncols,
        l = l,
        planter = planter,
        plotNumber = plotNumber,
        locationNames = locationNames,
        exptName = exptName,
        seed = seed,
        spread_reps = spread_reps,
        allow_fillers = allow_fillers,
        multiLocationData = TRUE,
        dist_method = "euclidean",
        border_penalization = 0.5,
        data = preps$list_locs,
        year = year
    )
    if (is.null(design_randomization$fieldBook)) {
        fieldhub_abort("multi_location_prep(): the p-rep designs of the locations could not be built.")
    }
    field_book_with_rep <- add_rep_column(df = design_randomization$fieldBook)
    design_randomization$infoDesign$id_design <- "MultiPrep"
    output <- list(
        infoDesign = design_randomization$infoDesign,
        min_pairwise_distance = design_randomization$min_pairwise_distance,
        reps_info = design_randomization$reps_info,
        layoutRandom = design_randomization$layoutRandom,
        pairsDistance = design_randomization$pairsDistance,
        plotNumber = design_randomization$plotNumber,
        binaryField = design_randomization$binaryField,
        fillerField = design_randomization$fillerField,
        dataEntry = design_randomization$dataEntry,
        genEntries = design_randomization$genEntries,
        treatments_with_reps = design_randomization$treatments_with_reps,
        treatments_with_no_reps = design_randomization$treatments_with_no_reps,
        fieldBook = field_book_with_rep,
        multi_location_data = preps$multi_location_data,
        list_locs = preps$list_locs,
        allocation = preps$allocation,
        size_locations = preps$size_locations
    )
    reproduction_parameters <- record_design_parameters(environment())
    output <- new_fieldhub_design(output, "multi_location_prep", parameters = reproduction_parameters)
    return(invisible(output))
}
