#' @title  Unreplicated designs using the sparse allocation approach
#' @param lines Number of genotypes, experimental lines or treatments.
#' @param checks Number of genotypes checks.
#' @param planter Option for \code{serpentine} or \code{cartesian} plot arrangement.
#' By default  \code{planter = 'serpentine'}.
#' @param l Number of locations or sites. By default  \code{l = 1}.
#' @param plotNumber Numeric vector with the starting plot number for each location.
#' By default \code{plotNumber = 101}.
#' @param copies_per_entry Number of copies per plant.
#' When design is \code{sparse} then \code{copies_per_entry} < \code{l}
#' @param exptName (optional) Name of the experiment.
#' @param locationNames (optional) Names each location.
#' @param nrows Number of rows in the field.
#' @param ncols Number of columns in the field.
#' @param sparse_list (optional) A class "Sparse" object generated by \code{do_optim()} function.
#' @param seed (optional) Real number that specifies the starting seed to obtain reproducible designs.
#' @param data (optional) Data frame with 2 columns: \code{ENTRY | NAME }. ENTRY must be numeric.
#'
#' @author Didier Murillo [aut],
#'         Salvador Gezan [aut],
#'         Ana Heilman [ctb]
#'
#' @param year (optional) Year recorded in the \code{YEAR} column of the field book.
#' By default the current year.
#' @param checksPercent (optional) Percentage of checks in each location, one of the
#' options available for the field. By default the last (largest) option.
#' @return A list with eight elements.
#' \itemize{
#'   \item \code{infoDesign} is a list with information on the design parameters.
#'   \item \code{layoutRandom} is a list with the randomization layout of each location.
#'   \item \code{plotsNumber} is a list with the plot number layout of each location.
#'   \item \code{data_entry} is a data frame with the data input.
#'   \item \code{fieldBook} is a data frame with the field book of all locations.
#'   \item \code{list_locs} is a list with each location list of entries.
#'   \item \code{allocation} is a matrix with the allocation of treatments.
#'   \item \code{size_locations} is a named vector with the number of lines
#'  allocated to each location.
#' }
#'
#' @references
#' Edmondson, R.N. Multi-level Block Designs for Comparative Experiments. JABES 25,
#' 500–522 (2020). https://doi.org/10.1007/s13253-020-00416-0
#'
#' @examples
#' sparse <- sparse_allocation(
#'   lines = 120,
#'   l = 4,
#'   copies_per_entry = 3,
#'   checks = 4,
#'   locationNames = c("LOC1", "LOC2", "LOC3", "LOC4"),
#'   seed = 1234
#' )
#' @section Reproducibility:
#' The result records effective inputs and the resolved seed in
#' \code{metadata$parameters}. Under the same package versions and RNG
#' settings, rebuild a result \code{x} with
#' \code{do.call(sparse_allocation, x$metadata$parameters)}.
#'
#' @export
sparse_allocation <- function(
    lines,
    nrows,
    ncols,
    l,
    planter = "serpentine",
    plotNumber,
    copies_per_entry,
    checks = NULL,
    exptName = NULL,
    locationNames,
    sparse_list,
    seed,
    data = NULL,
    year = NULL,
    checksPercent = NULL) {
    validate_locations(l)
    year <- resolve_year(year)
    # set a random seed if it is missing
    if (missing(seed)) seed <- NULL
    seed <- resolve_seed(seed, default = function() sample.int(10000, size = 1))
    local_design_seed(seed)
    if (missing(l)) fieldhub_abort("Please, define the number of locations for this design.")
    if (missing(locationNames) || length(locationNames) != l)  {
        default_names <- paste0("LOC", 1:l)
        if (!missing(locationNames)) {
            warn_default_location_names(locationNames, l, default_names)
        }
        locationNames <- default_names
    }
    if (missing(plotNumber) || length(plotNumber) != l) {
        default_plots <- seq(1, 1000 * l, by = 1000)[1:l]
        if (!missing(plotNumber)) {
            warn_default_plot_numbers(plotNumber, l, default_plots)
        }
        plotNumber <- default_plots
    }
    if (missing(exptName)) exptName <- "SparseExpt"
    if (missing(planter) || is.null(planter)) planter <- "serpentine"
    if (all(c("serpentine", "cartesian") != planter)) {
        fieldhub_abort("Input planter choice is unknown. Please, choose one: 'serpentine' or 'cartesian'.")
    }
    # Check if the reps per plant are mising
    if (missing(copies_per_entry)) {
        fieldhub_abort("You must specify the number of reps per plant")
    }
    validate_iteration_budget(copies_per_entry, "copies_per_entry")
    if (copies_per_entry >= l) fieldhub_abort("Please, enter copies_per_entry < l")
    if (is.null(checks)) fieldhub_abort("Please, define the number of checks for this design.")
    if (!missing(sparse_list)) {
        if (!inherits(sparse_list, "Sparse")) {
            fieldhub_abort("sparse_list must be an object of class 'Sparse'")
        }
        unrep <- sparse_list
    } else {
        unrep <- do_optim(
            design = "sparse",
            lines = lines,
            l = l,
            copies_per_entry = copies_per_entry,
            add_checks = TRUE,
            checks = checks,
            seed = seed
        )
    }
    # Merge user input data
    if (!is.null(data)) {
        unrep <- merge_user_data(
            optim_out = unrep,
            data = data,
            lines = lines,
            add_checks = TRUE,
            checks = checks
        )
    }
    # Define field dimensions (rows and columns)
    if (missing(nrows) || missing(ncols)) {
        lines_within_loc <- as.numeric(unrep$size_locations[1])
        t1 <- floor(lines_within_loc + lines_within_loc * 0.11)
        t2 <- ceiling(lines_within_loc + lines_within_loc * 0.20)
        t <- t1:t2
        non_primes <- t[!is_prime(t)]
        choices_list <- list()
        i <- 1
        for (n in non_primes) {
            choices_list[[i]] <- factor_subsets(n, diagonal = TRUE)$labels
            i <- i + 1
        }
        choices <- unlist(choices_list[!sapply(choices_list, is.null)])
        if (length(choices) == 0) {
            fieldhub_abort("There are no field dimension options available. Please specify nrows and ncols.")
        }
        dif <- vector(mode = "numeric", length = length(choices))
        for (option in seq_along(choices)) {
            dims <- unlist(strsplit(choices[[option]], " x "))
            dif[option] <- abs(as.numeric(dims[1]) - as.numeric(dims[2]))
        }
        df_choices <- data.frame(choices = choices, diff_dim = dif)
        df_choices <- df_choices[order(df_choices$diff_dim, decreasing = FALSE), ]
        dimensions <- unlist(strsplit(df_choices[1,1], " x "))
        nrows <- as.numeric(dimensions[1])
        ncols <- as.numeric(dimensions[2])
    }
    unrep_designs <- diagonal_arrangement(
        nrows = nrows,
        ncols = ncols,
        checks = checks,
        planter = planter,
        plotNumber = plotNumber,
        l = l,
        locationNames = locationNames,
        exptName = exptName,
        seed = seed,
        multiLocationData= TRUE,
        data = unrep,
        year = year,
        checksPercent = checksPercent
    )
    unrep_designs$infoDesign$id_design <- "Sparse"
    output <- list(
        infoDesign = unrep_designs$infoDesign,
        layoutRandom = unrep_designs$layoutRandom,
        plotsNumber = unrep_designs$plotsNumber,
        data_entry = unrep_designs$data_entry,
        fieldBook = unrep_designs$fieldBook,
        list_locs = unrep$list_locs,
        allocation = unrep$allocation,
        size_locations = unrep$size_locations
    )
    reproduction_parameters <- record_design_parameters(environment())
    output <- new_fieldhub_design(output, "sparse_allocation", parameters = reproduction_parameters)
    return(invisible(output))
}
